name: daily_coding_routine-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - pandas
  - scikit-learn
  - jupyter
  - matplotlib
  - seaborn
  - ipykernel
  - langchain
  - pip
  - pip:
    - langchain