name: learn_langchain-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pandas
  - scikit-learn
  - jupyter
  - matplotlib
  - seaborn
  - ipykernel
  - langchain
  - langchain-community
  - langchainhub
  - pip
  - pip:
    - neo4j
    - langchain-neo4j
    - cohere
    - langchain-cohere